# Generated by Django 5.2 on 2025-04-06 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FitFair', '0010_alter_meal_meal_of_the_day'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meal',
            name='mealtype',
        ),
        migrations.DeleteModel(
            name='MealType',
        ),
    ]
